# Generated by Django 4.0.4 on 2022-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=20)),
                ('choice_text', models.CharField(choices=[('difficult', 'difficult'), ('easy', 'easy')], max_length=20)),
                ('votes', models.IntegerField()),
            ],
            options={
                'ordering': ('votes',),
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('timestamp', models.DateField()),
            ],
            options={
                'ordering': ('text',),
            },
        ),
    ]
